### ISSUE TITLE
Create incomplete outputs

### ISSUE THREAD

**Issue by ok1hra** [adamgreig/agg-kicad#36]
Error messages:
Traceback (most recent call last):
  File "/home/dan/kicad/agg-kicad-master/scripts/stickerbom.py", line 454, in <module>
    main(xmlpath, pdfpath)
  File "/home/dan/kicad/agg-kicad-master/scripts/stickerbom.py", line 446, in main
    label_height-14, line.refs)
  File "/home/dan/kicad/agg-kicad-master/scripts/stickerbom.py", line 208, in render
    scale_x = max_w / bound_width
ZeroDivisionError: float division by zero

[bd.pdf](https://github.com/adamgreig/agg-kicad/files/128887/bd.pdf)

**Comment by adamgreig** [comment]
Do you have an example file that's causing this problem? My guess is it's finding the required bounding area around components is zero width, causing problems.

**Comment by ok1hra** [comment]
if anything is missing, i add

[bd.zip](https://github.com/adamgreig/agg-kicad/files/128890/bd.zip)

**Comment by adamgreig** [comment]
Hi @ok1hra, thanks for the bug report! I'm sorry it took a while to get around to fixing it. The problem was that P13 has just the one pad, and when its extent was computed, the pad's size was not taken into account, so it had a zero-sized highlight area, which caused the problem.

I've updated StickerBOM to include the size of the pads when computing the extents, so the problem should now be fixed - and seems to work fine on your PCB.

**Comment by ok1hra** [comment]
Thanks for fix it, now generate without errors.
But otputs pile up in one page [bd.pdf](https://github.com/adamgreig/agg-kicad/files/177464/bd.pdf).

**Comment by adamgreig** [comment]
Please try with `python3` instead of `python`, sounds like you are experiencing issue #45

**Comment by ok1hra** [comment]
Confirming you're right, now works correctly, thanks again.
